spring.application.name=authapp
spring.datasource.url= jdbc:postgresql://postgres-2:5432/logindbinv
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.data.redis.host=redis
spring.data.redis.port=6379

management.metrics.enable.kafka=true
spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.enable.spring.data=true
spring.jpa.properties.hibernate.generate_statistics=true
management.metrics.enable.hibernate=true
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true